language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
    - php: 7.3
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.4
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
    - php: 7.4
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 8.0
      env:
        - DEPENDENCIES=""
    - php: 8.0
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer require friendsofphp/php-cs-fixer
  - composer update --prefer-dist $DEPENDENCIES
  - cp .env.example .env
  - php artisan key:generate --ansi

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/php-cs-fixer fix . --config .php_cs.laravel.php -v --diff --dry-run ; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
