language: php
php:
  - 7.3

before_script:
  - composer global require fabpot/php-cs-fixer
  - composer update
  - composer install --dev

script:
  - phpunit
  - php php-cs-fixer --diff --dry-run -v fix
